version: "2"

services:

  mariadb:
    image: wodby/mariadb:10.4-3.8.0
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - 3306:3306

  php:
    image: wodby/drupal-php:7.3
    environment:
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/nginx:1.17-5.8.9
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/build
      NGINX_VHOST_PRESET: drupal8
    volumes:
      - ./:/var/www/html
    ports:
    - "8080:80"

  # If you would like to see what is going on you can run the following on your host:
  # docker run --rm -p 4444:4444 -p 5900:5900 --network="host" selenium/standalone-chrome-debug:latest
  # Newer version of this image might run into this issue:
  # @link https://github.com/elgalu/docker-selenium/issues/20
  selenium:
    image: selenium/standalone-chrome-debug:3
    expose:
    - '4444'
    environment:
    - DISPLAY=:99
    - SE_OPTS=-debug
    - SCREEN_WIDTH=1280
    - SCREEN_HEIGHT=800
    - VNC_NO_PASSWORD=1
    ports:
    - '4444:4444'
    - '5900:5900'
    volumes:
    - /dev/shm:/dev/shm

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025